spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml

jws:
  sharedKey: bdc6e4de-a1b9-49d4-bdec-39c2f0c62261






